# Generated by Django 6.0.4 on 2026-07-22 03:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('licencia', models.CharField(max_length=50)),
                ('tipo_licencia', models.CharField(choices=[('A', 'Tipo A'), ('B', 'Tipo B'), ('C', 'Tipo C'), ('D', 'Tipo D'), ('E', 'Tipo E')], default='C', max_length=2)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('placa_vehiculo', models.CharField(max_length=20)),
                ('marca_vehiculo', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo_vehiculo', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=30, unique=True)),
                ('remitente_nombre', models.CharField(max_length=150)),
                ('remitente_telefono', models.CharField(max_length=20)),
                ('destinatario_nombre', models.CharField(max_length=150)),
                ('destinatario_telefono', models.CharField(max_length=20)),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('volumen_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fecha_despacho', models.DateField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('Estándar', 'Estándar'), ('Express', 'Express'), ('Urgente', 'Urgente')], default='Estándar', max_length=20)),
                ('estado_actual', models.CharField(choices=[('Registrado', 'Registrado'), ('En Bodega', 'En Bodega'), ('En Tránsito', 'En Tránsito'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], default='Registrado', max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paquetes', to='Info.conductor')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialPaquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=30)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='Info.paquete')),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
