# Generated by Django 6.0.4 on 2026-07-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='destinatario_correo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo del Destinatario'),
        ),
    ]
